//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rythm.Client.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rythm.Client.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address must match the pattern of ip addresses.
        /// </summary>
        internal static string AddressErrorMessage {
            get {
                return ResourceManager.GetString("AddressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonStyleDark.xaml.
        /// </summary>
        internal static string ButtonStyleDark {
            get {
                return ResourceManager.GetString("ButtonStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonStyleLight.xaml.
        /// </summary>
        internal static string ButtonStyleLight {
            get {
                return ResourceManager.GetString("ButtonStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatButton {
            get {
                return ResourceManager.GetString("ChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatListBoxBackgroundStyleDark.xaml.
        /// </summary>
        internal static string ChatListBoxBackgroundStyleDark {
            get {
                return ResourceManager.GetString("ChatListBoxBackgroundStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatListBoxBackgroundStyleLight.xaml.
        /// </summary>
        internal static string ChatListBoxBackgroundStyleLight {
            get {
                return ResourceManager.GetString("ChatListBoxBackgroundStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatListBoxItemStyleDark.xaml.
        /// </summary>
        internal static string ChatListBoxItemStyleDark {
            get {
                return ResourceManager.GetString("ChatListBoxItemStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatListBoxItemStyleLight.xaml.
        /// </summary>
        internal static string ChatListBoxItemStyleLight {
            get {
                return ResourceManager.GetString("ChatListBoxItemStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientsListBoxBackgroundStyleDark.xaml.
        /// </summary>
        internal static string ClientsListBoxBackgroundStyleDark {
            get {
                return ResourceManager.GetString("ClientsListBoxBackgroundStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientsListBoxBackgroundStyleLight.xaml.
        /// </summary>
        internal static string ClientsListBoxBackgroundStyleLight {
            get {
                return ResourceManager.GetString("ClientsListBoxBackgroundStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientsListBoxItemStyleDark.xaml.
        /// </summary>
        internal static string ClientsListBoxItemStyleDark {
            get {
                return ResourceManager.GetString("ClientsListBoxItemStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientsListBoxItemStyleLight.xaml.
        /// </summary>
        internal static string ClientsListBoxItemStyleLight {
            get {
                return ResourceManager.GetString("ClientsListBoxItemStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonBackgroundStyleDark.xaml.
        /// </summary>
        internal static string CommonBackgroundStyleDark {
            get {
                return ResourceManager.GetString("CommonBackgroundStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonBackgroundStyleLight.xaml.
        /// </summary>
        internal static string CommonBackgroundStyleLight {
            get {
                return ResourceManager.GetString("CommonBackgroundStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonChat.
        /// </summary>
        internal static string CommonChat {
            get {
                return ResourceManager.GetString("CommonChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomWindowChromeDark.xaml.
        /// </summary>
        internal static string CustomWindowChromeDark {
            get {
                return ResourceManager.GetString("CustomWindowChromeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomWindowChromeLight.xaml.
        /// </summary>
        internal static string CustomWindowChromeLight {
            get {
                return ResourceManager.GetString("CustomWindowChromeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EventsButton {
            get {
                return ResourceManager.GetString("EventsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridStyleDark.xaml.
        /// </summary>
        internal static string GridStyleDark {
            get {
                return ResourceManager.GetString("GridStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridStyleLight.xaml.
        /// </summary>
        internal static string GridStyleLight {
            get {
                return ResourceManager.GetString("GridStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login cannot be empty.
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginTextBlockStyleDark.xaml.
        /// </summary>
        internal static string LoginTextBlockStyleDark {
            get {
                return ResourceManager.GetString("LoginTextBlockStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginTextBlockStyleLight.xaml.
        /// </summary>
        internal static string LoginTextBlockStyleLight {
            get {
                return ResourceManager.GetString("LoginTextBlockStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string MessageClientOkColor {
            get {
                return ResourceManager.GetString("MessageClientOkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string MessageServerOkColor {
            get {
                return ResourceManager.GetString("MessageServerOkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrollViewerStyleDark.xaml.
        /// </summary>
        internal static string ScrollViewerStyleDark {
            get {
                return ResourceManager.GetString("ScrollViewerStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrollViewerStyleLight.xaml.
        /// </summary>
        internal static string ScrollViewerStyleLight {
            get {
                return ResourceManager.GetString("ScrollViewerStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockStyleDark.xaml.
        /// </summary>
        internal static string TextBlockStyleDark {
            get {
                return ResourceManager.GetString("TextBlockStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockStyleLight.xaml.
        /// </summary>
        internal static string TextBlockStyleLight {
            get {
                return ResourceManager.GetString("TextBlockStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxStyleDark.xaml.
        /// </summary>
        internal static string TextBoxStyleDark {
            get {
                return ResourceManager.GetString("TextBoxStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxStyleLight.xaml.
        /// </summary>
        internal static string TextBoxStyleLight {
            get {
                return ResourceManager.GetString("TextBoxStyleLight", resourceCulture);
            }
        }
    }
}
