//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rythm.Client.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rythm.Client.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The address must match the pattern of ip addresses.
        /// </summary>
        internal static string AddressErrorMessage {
            get {
                return ResourceManager.GetString("AddressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ButtonStyleDark.xaml.
        /// </summary>
        internal static string ButtonStyleDark {
            get {
                return ResourceManager.GetString("ButtonStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ButtonStyleLight.xaml.
        /// </summary>
        internal static string ButtonStyleLight {
            get {
                return ResourceManager.GetString("ButtonStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat.
        /// </summary>
        internal static string ChatButton {
            get {
                return ResourceManager.GetString("ChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChatListBoxBackgroundStyleDark.xaml.
        /// </summary>
        internal static string ChatListBoxBackgroundStyleDark {
            get {
                return ResourceManager.GetString("ChatListBoxBackgroundStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChatListBoxBackgroundStyleLight.xaml.
        /// </summary>
        internal static string ChatListBoxBackgroundStyleLight {
            get {
                return ResourceManager.GetString("ChatListBoxBackgroundStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChatListBoxItemStyleDark.xaml.
        /// </summary>
        internal static string ChatListBoxItemStyleDark {
            get {
                return ResourceManager.GetString("ChatListBoxItemStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChatListBoxItemStyleLight.xaml.
        /// </summary>
        internal static string ChatListBoxItemStyleLight {
            get {
                return ResourceManager.GetString("ChatListBoxItemStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClientsListBoxBackgroundStyleDark.xaml.
        /// </summary>
        internal static string ClientsListBoxBackgroundStyleDark {
            get {
                return ResourceManager.GetString("ClientsListBoxBackgroundStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClientsListBoxBackgroundStyleLight.xaml.
        /// </summary>
        internal static string ClientsListBoxBackgroundStyleLight {
            get {
                return ResourceManager.GetString("ClientsListBoxBackgroundStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClientsListBoxItemStyleDark.xaml.
        /// </summary>
        internal static string ClientsListBoxItemStyleDark {
            get {
                return ResourceManager.GetString("ClientsListBoxItemStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClientsListBoxItemStyleLight.xaml.
        /// </summary>
        internal static string ClientsListBoxItemStyleLight {
            get {
                return ResourceManager.GetString("ClientsListBoxItemStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CommonBackgroundStyleDark.xaml.
        /// </summary>
        internal static string CommonBackgroundStyleDark {
            get {
                return ResourceManager.GetString("CommonBackgroundStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CommonBackgroundStyleLight.xaml.
        /// </summary>
        internal static string CommonBackgroundStyleLight {
            get {
                return ResourceManager.GetString("CommonBackgroundStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CommonChat.
        /// </summary>
        internal static string CommonChat {
            get {
                return ResourceManager.GetString("CommonChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CustomWindowChromeDark.xaml.
        /// </summary>
        internal static string CustomWindowChromeDark {
            get {
                return ResourceManager.GetString("CustomWindowChromeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CustomWindowChromeLight.xaml.
        /// </summary>
        internal static string CustomWindowChromeLight {
            get {
                return ResourceManager.GetString("CustomWindowChromeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Events.
        /// </summary>
        internal static string EventsButton {
            get {
                return ResourceManager.GetString("EventsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login cannot be empty.
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Green.
        /// </summary>
        internal static string MessageClientOkColor {
            get {
                return ResourceManager.GetString("MessageClientOkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gray.
        /// </summary>
        internal static string MessageServerOkColor {
            get {
                return ResourceManager.GetString("MessageServerOkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ScrollViewerStyleDark.xaml.
        /// </summary>
        internal static string ScrollViewerStyleDark {
            get {
                return ResourceManager.GetString("ScrollViewerStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ScrollViewerStyleLight.xaml.
        /// </summary>
        internal static string ScrollViewerStyleLight {
            get {
                return ResourceManager.GetString("ScrollViewerStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBlockStyleDark.xaml.
        /// </summary>
        internal static string TextBlockStyleDark {
            get {
                return ResourceManager.GetString("TextBlockStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBlockStyleLight.xaml.
        /// </summary>
        internal static string TextBlockStyleLight {
            get {
                return ResourceManager.GetString("TextBlockStyleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBoxStyleDark.xaml.
        /// </summary>
        internal static string TextBoxStyleDark {
            get {
                return ResourceManager.GetString("TextBoxStyleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBoxStyleLight.xaml.
        /// </summary>
        internal static string TextBoxStyleLight {
            get {
                return ResourceManager.GetString("TextBoxStyleLight", resourceCulture);
            }
        }
    }
}
